### ISSUE TITLE
'KeyWrap' is only available in iOS 15.0 or newer

### ISSUE THREAD

**Issue by kuldar-daniel** [beatt83/jose-swift#30]
**Describe the bug**

Unable to compile the library due to the minimum iOS version for the package being iOS 14, however it uses Apple's API-s that are supported from iOS 15+

<img width="400" alt="Screenshot 2024-06-28 at 11 59 21" src="https://github.com/beatt83/jose-swift/assets/26465109/d56abfb8-2e88-45a3-ba7f-6112edd1180a">

**Comment by beatt83** [comment]
Hi @kuldar-daniel .

Can you check the version you're using? Im pretty sure this is already fixed in this commit: https://github.com/beatt83/jose-swift/commit/28dc857de720ffc6c5f179d812e0418074923f78

Version 3.1.0

**Comment by kuldar-daniel** [comment]
That's correct, that fixed it. Silly me for not noticing I'm not on latest. Thank you!
