### ISSUE TITLE
Symmetric sample code does not compile

### ISSUE THREAD

**Issue by dscreve** [beatt83/jose-swift#35]
I'm trying to do encrypted JWT with A256GCM, using the example below : 

https://beatt83.github.io/jose-swift/documentation/jose-swift/encryptingjwt#Example

Actually, this example does not even compile....A256GCM should be written .a256CM and there a lot of others errors.

I've succeeded to write something, but I have a JSONWebEncryption.JWE.JWEError.missingCek error when calling JWT.verify.

Here is my piece of code : 

struct JWTContent : Codable {
    var foo : String
}

let expiredAt=Date().addingTimeInterval(60)
let header = DefaultJWEHeaderImpl(
    keyManagementAlgorithm: .direct,
    encodingAlgorithm: .a256GCM
)

let kekData = Data(count: 256 / 8)
let symmetricKey =  JWK(keyType: .octetSequence, key: kekData)

let tokenData = JWTContent(foo:"bar")
let mockClaims = DLTAClaim<JWTContent>(
    body: tokenData,
    iss: "DLTA Studio",
    exp: expiredAt)

let jwt = try JWT.encrypt(
    payload: mockClaims,
    protectedHeader: header,
 //   unprotectedHeader: nil,
    senderKey: nil,
    recipientKey: symmetricKey,
    sharedKey:nil
)

let jwtString = jwt.jwtString

let verifiedJWT = try JWT.verify(jwtString: jwtString, recipientKey: symmetricKey)
let verifiedPayload = verifiedJWT.payload

**Comment by beatt83** [comment]
Hey mate. So yeah the examples need some updates indeed, but with this I know what improvements to make ;) .
On your case you actually found a bug on JWT decryption for Direct mode, where the shared key parameter is not in the function parameters.

I fixed it in this PR and when merged I will release a new version: https://github.com/beatt83/jose-swift/pull/36

The API is a bit confusing as well because it has `signerKey`, `senderKey`, `recipientKey` and `sharedKey` and `cek`, this is something I noted and will change in the next major version.

I share below how the code you provided works, since it is `DIRECT` you can see while encrypting I pass the `kekData` as the `cek` parameter and when decrypting I pass the JWK as the sharedKey, this only happens when the key algorithm is `DIRECT`, be aware that direct is not advised for production ;).

I give you 2 more examples one to use claims builder instead of creating a structure for your JWT payload, and how the encryption would work for other key management algorithm.

Here is the example on how it works:

```
        struct JWTContent : Codable {
            var foo : String
        }
        
        struct DLTAClaim : Codable {
            var body : JWTContent
            var iss : String
            var exp : Date
        }
        
        let expiredAt = Date().addingTimeInterval(60)
        
        let header = DefaultJWEHeaderImpl(
            keyManagementAlgorithm: .direct,
            encodingAlgorithm: .a256GCM
        )

        let kekData = Data(count: 256 / 8)
        let symmetricKey = JWK(keyType: .octetSequence, key: kekData)
        
        let tokenData = JWTContent(foo:"bar")
        let mockClaims = DLTAClaim(
            body: tokenData,
            iss: "DLTA Studio",
            exp: expiredAt
        )
        
        let jwt = try JWT.encrypt(
            payload: mockClaims,
            protectedHeader: header,
            senderKey: nil,
            recipientKey: nil,
            sharedKey: symmetricKey,
            cek: kekData
        )

        let jwtString = jwt.jwtString

        let verifiedJWT = try JWT.verify(jwtString: jwtString, sharedKey: symmetricKey)
        let verifiedPayload = verifiedJWT.payload
```

Create a encrypted JWT with the claims DSL.
```
        let expiredAt = Date().addingTimeInterval(60)
        
        let header = DefaultJWEHeaderImpl(
            keyManagementAlgorithm: .direct,
            encodingAlgorithm: .a256GCM
        )

        let kekData = Data(count: 256 / 8)
        
        let jwt = try JWT.encrypt(
            claims:  {
                ObjectClaim(key: "body") {
                    StringClaim(key: "foo", value: "bar")
                }
                IssuerClaim(value: "DLTA Studio")
                ExpirationTimeClaim(value: expiredAt)
            },
            protectedHeader: header,
            senderKey: nil,
            recipientKey: nil,
            sharedKey: nil,
            cek: kekData
        )

        let jwtString = jwt.jwtString

        let verifiedJWT = try JWT.verify(jwtString: jwtString, sharedKey: JWK(keyType: .octetSequence, key: kekData))
        let verifiedPayload = verifiedJWT.payload
```

Create a encrypted JWT with ecdhESA256KW.
```
        let expiredAt = Date().addingTimeInterval(60)
        
        let header = DefaultJWEHeaderImpl(
            keyManagementAlgorithm: .ecdhESA256KW,
            encodingAlgorithm: .a256GCM
        )

        let key = Curve25519.KeyAgreement.PrivateKey()
        
        let jwt = try JWT.encrypt(
            claims:  {
                ObjectClaim(key: "body") {
                    StringClaim(key: "foo", value: "bar")
                }
                IssuerClaim(value: "DLTA Studio")
                ExpirationTimeClaim(value: expiredAt)
            },
            protectedHeader: header,
            senderKey: nil,
            recipientKey: key,
            sharedKey: nil
        )

        let jwtString = jwt.jwtString

        let verifiedJWT = try JWT.verify(jwtString: jwtString, recipientKey: key)
        let verifiedPayload = verifiedJWT.payload
```

**Comment by beatt83** [comment]
Ive released the version with the fix for the bug: https://github.com/beatt83/jose-swift/releases/tag/4.0.2

**Comment by dscreve** [comment]
Thanks for your helps.

I did’nt know that direct was not recommended for production.

In the meantime, I succeeded in making to work by using a256GCMKW as keyManagmentAlgorithm.

I see that you used  ecdhESA256KW. Is it better than a256GCMKW ?

Regards,


--
David Scrève - DLTA Studio
Gérant - 06 27 69 58 14
***@***.***
4249534F5553

**Comment by beatt83** [comment]
It depends on the usage you're going to give.

A256GCMKW both parties share the same symmetric key, and they encrypt and decrypt the content encryption key with the symmetric key, its more used when both parties have already access to the key.

ECDHES/ECDH1PU is basically a protocol using Elliptic curve keys each party has their own private/public keys and they establish a shared secret between them.

ECDHES and ECDH1PU is more used lets say for chats as an example/
