### ISSUE TITLE
Problem with keyManagementAlg: .dir and encryptionAlgorithm: .a256GCM

### ISSUE THREAD

**Issue by leftkaramolegos** [beatt83/jose-swift#9]
When I try to run the code bellow

let serialization = try JWE(
    payload: payload,
    keyManagementAlg: .dir,
    encryptionAlgorithm: .a256GCM,
    recipientKey: keyJWK
)

the encryption throws exception

**Comment by beatt83** [comment]
Hi @leftkaramolegos. 

Direct doesn't use any key exchange protocol, so your providing a recipientKey doesn't do anything for the process.
You should and need to provide a `cek` like in the example below.

What you have here doesn't produce any error, although since internally it will create automatically a CEK, you will not be able to decrypt.

You can check the code below to check on how to achieve this.

```
    func testDirectJWE() throws {
        let payload = try "Test".tryToData()
        
        let keyAlg = KeyManagementAlgorithm.direct
        let encAlg = ContentEncryptionAlgorithm.a256GCM
        
        let secretKey = try encAlg.encryptor.generateCEK()
        let testJWK = JWK(keyType: .octetSequence, key: secretKey)
        
        let jwe = try JWE(
            payload: payload,
            keyManagementAlg: .direct,
            encryptionAlgorithm: .a256GCM,
            cek: testJWK.key
        ).compactSerialization()
        
        let decrypted = try JWE(compactString: jwe)
            .decrypt(sharedKey: testJWK)
        
        XCTAssertEqual(payload, decrypted)
    }
```

**Comment by leftkaramolegos** [comment]
I'm terrible sorry, probably it's my mistake.
Can you tell me how do I get a  JWK from a symmetric key?

**Comment by beatt83** [comment]
Yup I provided a public API for that.

A symmetric key is a a SecureRandom of bytes, you can use this one and switch for the encryption algorithm you use.

```
import JSONWebAlgorithms

let symmetricKey = try ContentEncryptionAlgorithm.a256GCM.encryptor.generateCEK()

// If you want a JWK of this just initialise like so
let symmetricJWK = JWK(keyType: .octetSequence, key: symmetricKey)
```
